---
title: "Prostorové modely na Pražském trhu nemovitostí"
author: Petr Hrobař
output: github_document
---
  
```{r set knitr options, echo = FALSE}
# Defaultní nastavení
knitr::opts_chunk$set(echo = F,
                      message = FALSE,
                      warning = FALSE,
                      fig.width=12, fig.height=10)
```



In this study we apply ***Spatial Econometrics models*** and evaluate
flats prices. We suppose that **price** of the flat is not only the
function of flat’s own characteristics but also function of its
neighbourhood characteristics.

- Firstly we test for spatial dependency
- Then applying spatial models

Data Distribution:
```{r}
library(ggmap)
df <- read.csv("Dataset_Filtered_cleaned.csv", sep = ",")

CORD = cbind(df$gps.lon, df$gps.lat)
CORD[ ,1] <- CORD[ ,1] + runif(min = -10E-4, max = 10E-4, dim(CORD)[1])
CORD[ ,2] <- CORD[ ,2] + runif(min = -10E-4, max = 10E-4, dim(CORD)[1])

bboxPrague <- c(14.22,49.94,14.71,50.18)
ggMapPrague <- get_map(location = bboxPrague, source = "osm",maptype = "terrain", crop = TRUE, zoom = 12)

  ggmap(ggMapPrague) + 
  geom_point(data = df, aes(x = CORD[ ,1], y = CORD[ ,2]), color = "black", size = 0.75, alpha = 0.7) + 
    theme(legend.justification=c(0, 1), legend.position=c(0.05, 0.95),
        legend.text=element_text(size=7), legend.title=element_text(size=7),
        legend.key.size = unit(0.2, "cm"),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        legend.box.background = element_rect(colour = "black", size = 0.05)
        ) +
  xlab(" ") + 
  ylab(" ") + 
  ggtitle("Distribuce pozorování")
```


